### PR TITLE
DB fix and job early-exit

### PR DESCRIPTION
**Pull request by umbrant**
Please see commit messages for details.

### CODE REVIEW

**Comment by umbrant** [comment]
@toddlipcon could you please review?

If the schema fix looks good, we'll want to ALTER TABLE dist_test_tasks to match the new schema.

**Comment by umbrant** [comment]
I'll also add that I tested this change locally with TestFailAlways in the grind sample project, and saw the job successfully canceled.

We currently do not differentiate between a finished or canceled job/task on the UI. I think this would be an easy improvement, since I think it sets a special -1 status code.

**Comment by umbrant** [comment]
Also here's the MySQL error if you're interested. Googling shows there's a config to allow this, but since I think it's causing our negative task durations, I think it's a good fix.

_mysql_exceptions.OperationalError: (1067, "Invalid default value for 'start_timestamp'")

**Comment by toddlipcon** [comment]
this lgtm but for some reason I seem to have lost write access to this repo...

**Comment by umbrant** [comment]
Thanks for the review!

**Pull request merged**
