### PR TITLE
Reorganize source repository.

### PR DESCRIPTION
**Pull request by umbrant**
* Moved source files from root to "infra" folder
* Moved virtualenv creation into the bin wrappers
* Removed extraneous sample_job.json file
* Updated README with simpler runsteps

I tested this by running "git clean -xdf", starting a local cluster,
"./setup.sh", and running grind. Job completed successfully. Trace view works.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Any update on this? :smiley: 

I think this PR will technically & legally (i.e. `LICENSE`) make it easy for people those interested in make a contribution to this project.

As I talked to @umbrant at ApacheCon, I'm very interested in this project :heart:

**Comment by umbrant** [comment]
Todd said I can just merge this, so doing so :)

**Comment by umbrant** [comment]
Thanks Akihiro for the interest, let's try and get your PRs reviewed and merged. I apologize for the delay; both myself and Todd have been travelling a lot over the last two weeks. We also have a new maintainer coming up to speed which will hopefully help move things along.

**Comment by terabyte** [comment]
That's me!  =) greetings all - I am watching from the bleachers right now

**Comment by AkihiroSuda** [comment]
Thank you @umbrant and hello @terabyte :smiley:

**Pull request merged**
